"""empty message

Revision ID: 121ad6454a4b
Revises: 
Create Date: 2021-06-03 08:18:08.055195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121ad6454a4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists_genres_pivot', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.drop_constraint('artists_genres_pivot_genere_id_fkey', 'artists_genres_pivot', type_='foreignkey')
    op.create_foreign_key(None, 'artists_genres_pivot', 'Genre', ['genre_id'], ['id'])
    op.drop_column('artists_genres_pivot', 'genere_id')
    op.add_column('venus_genres_pivot', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.drop_constraint('venus_genres_pivot_genere_id_fkey', 'venus_genres_pivot', type_='foreignkey')
    op.create_foreign_key(None, 'venus_genres_pivot', 'Genre', ['genre_id'], ['id'])
    op.drop_column('venus_genres_pivot', 'genere_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venus_genres_pivot', sa.Column('genere_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venus_genres_pivot', type_='foreignkey')
    op.create_foreign_key('venus_genres_pivot_genere_id_fkey', 'venus_genres_pivot', 'Genre', ['genere_id'], ['id'])
    op.drop_column('venus_genres_pivot', 'genre_id')
    op.add_column('artists_genres_pivot', sa.Column('genere_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'artists_genres_pivot', type_='foreignkey')
    op.create_foreign_key('artists_genres_pivot_genere_id_fkey', 'artists_genres_pivot', 'Genre', ['genere_id'], ['id'])
    op.drop_column('artists_genres_pivot', 'genre_id')
    # ### end Alembic commands ###
