"""empty message

Revision ID: 47717396cc2f
Revises: c47eff618921
Create Date: 2021-05-28 08:05:49.893184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47717396cc2f'
down_revision = 'c47eff618921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists_generes_pivot',
    sa.Column('genere_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genere_id'], ['Genere.id'], ),
    sa.PrimaryKeyConstraint('genere_id', 'artist_id')
    )
    op.add_column('Artist', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website')
    op.drop_table('artists_generes_pivot')
    # ### end Alembic commands ###
