"""empty message

Revision ID: 803e1411a032
Revises: 3059d8c4b9e4
Create Date: 2021-05-27 08:04:16.087416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803e1411a032'
down_revision = '3059d8c4b9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    # ### end Alembic commands ###
